### ISSUE TITLE
Problem with tailwind config and colors

### ISSUE THREAD

**Issue by mingan666** [ajaen4/goth-complete-setup#1]
Hi,

I'm new to both golang and all other parts of the stack so I was hoping to get started with help of your setup.
However, when I try to follow the instructions, i get the following error during `make run`

```
file:///home/xxx/src/tmp/goth-complete-setup/tailwind.config.js:6
      colors: require("tailwindcss/colors"),
```

Once I comment out the theme part in the tailwind.config.js the build runs without issues.

**Comment by ajaen4** [comment]
Hi @mingan666,

Could you check your node version with the following command?

`
node --version
`

I suspect your version is too old and doesn't support the require command. Could you send me the complete error message?

Regards.

**Comment by mingan666** [comment]
Sure here is some version info:

```
$ node --version
v23.2.0

$ npm --version
10.9.0
```

The error part of the output from the `make run` cmd:
```
warn - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
warn - Update your configuration file to silence this warning.
(node:255217) ExperimentalWarning: CommonJS module /home/anru/src/tmp/test/node_modules/tailwindcss/lib/lib/load-config.js is loading ES Module /home/anru/src/tmp/test/tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/anru/src/tmp/test/tailwind.config.js:6
      colors: require("tailwindcss/colors"),
              ^

ReferenceError: require is not defined
    at file:///home/anru/src/tmp/test/tailwind.config.js:6:15
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1380:24)
    at Module._compile (node:internal/modules/cjs/loader:1532:5)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
    at Module.load (node:internal/modules/cjs/loader:1307:32)
    at Function._load (node:internal/modules/cjs/loader:1121:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

Node.js v23.2.0
failed to build, error: exit status 1

```

**Comment by mingan666** [comment]
Sure here is some version info:

```
$ node --version
v23.2.0

$ npm --version
10.9.0
```

The error part of the output from the `make run` cmd:
```
warn - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
warn - Update your configuration file to silence this warning.
(node:255217) ExperimentalWarning: CommonJS module /home/anru/src/tmp/test/node_modules/tailwindcss/lib/lib/load-config.js is loading ES Module /home/anru/src/tmp/test/tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/xxx/src/tmp/test/tailwind.config.js:6
      colors: require("tailwindcss/colors"),
              ^

ReferenceError: require is not defined
    at file:///home/xxx/src/tmp/test/tailwind.config.js:6:15
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1380:24)
    at Module._compile (node:internal/modules/cjs/loader:1532:5)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
    at Module.load (node:internal/modules/cjs/loader:1307:32)
    at Function._load (node:internal/modules/cjs/loader:1121:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

Node.js v23.2.0
failed to build, error: exit status 1

```

**Comment by ajaen4** [comment]
I changed the tailwind config file to be compatible with any node version. I tested it with v23.2.0 and it looks like its solved. 

Let me know if it works for you.

**Comment by mingan666** [comment]
Thanks! Seems to work perfect now.

**Comment by ajaen4** [comment]
Great. If you find this repo useful, feel free to give it a star 😉
